<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Students [
    <!ELEMENT Students (id,name,course)*>   <!-- extendable -->
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT course (#PCDATA)>
]>
<Students>
    <id></id>
    <name></name>
    <course></course>

    <id></id>
    <name></name>
    <course></course>
</Students>